### ISSUE TITLE
Bosh error

### ISSUE THREAD

**Issue by cjconstante** [jsxc/xmpp-cloud-auth#29]
I just install Nextcloud on Ubuntu 16, i pass all the issues i found, but now i get this in apache log: AH00898: Error reading from remote server returned by /http-bind/
My vhost configuration is:
ProxyPass /http-bind/ http://localhost:5280/http-bind/
        ProxyPassReverse /http-bind/ http://localhost:5280/http-bind/
        ProxyPreserveHost On
When i try by browser i get:
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /http-bind/.
Reason: Error reading from remote server

When i try to configure javascript xmpp chat in nextcloud, i type the domain and url bosh and get this:
BOSH server NOT reachable or misconfigured.
502 Proxy Error

Please, help me!

**Comment by MarcelWaldvogel** [comment]
Is your XMPP server configured to serve BoSH requests on port 5280? What hapens if you point your browser directly at the URL behind the proxy? (On the machine itself, use a browser, possibly console-based, such as `lynx`; or if the port is also reachable from your work machine, point it to `http://<your-xmpp-server-name>:5280/http-bind/`

This has nothing to do with XMPP-Cloud-Auth, more with your XMPP server; so you might be able to find more help there. BTW: Which XMPP server are you using?

**Comment by cjconstante** [comment]
I am using ejabberd. I configure it as the guide requested with port 5280 http-bind module. That URL is not reached by browser, I got the errors mentioned.
I had to used an external bosh server and worked. I don't know why ejabberd did not open 5280 port.

--
Cristian Constante

**Comment by MarcelWaldvogel** [comment]
Here are some relevant excerpts from my BoSH-enabled `ejabberd.yml` for *ejabberd 17.07*:

```YaML
modules:
  mod_bosh: {}

# More helpful logging
trusted_proxies:
  - "127.0.0.1"
  - "::1"
  - "localhost"
  - "::FFFF:127.0.0.1" # This is the one which works here, but others might catch in other environments

listen:
  - 
    port: 5280
    ip: "::"
    module: ejabberd_http
    http_bind: true
```

What does `netstat -ntap | grep 5280` say?

(Closing as it is not an `xmpp-cloud-auth` issue, but feel free to continue)
